package shan;

/**
 * Accepts a response generated by a Shan command.
 */
@FunctionalInterface
public interface ResponseSink {
    /**
     * Receives a message that should be shown to the user.
     *
     * @param message Message generated by a command.
     */
    void showMessage(String message);
}
